### ISSUE TITLE
When go get github.com/chmike/domain@latest , just get v1.0.1.  And  not release on pkg.go.dev

### ISSUE THREAD

**Issue by hi-glenn** [chmike/domain#2]
https://pkg.go.dev/github.com/chmike/domain?tab=versions

**Comment by chmike** [comment]
Thank you very much for pointing out this problem that I'll fix ASAP. 
The reason is because I named the latest version v1.1 instead of v1.1.0.

**Comment by chmike** [comment]
Release tag changed. I guess we need to wait a bit for the change to be taken in account.
